name: AWS Production - Pipeline

on:
  schedule:
    - cron: "0 3 * * 1-5" # Runs between 8-9 AM GMT+5 Mon-Fri

  workflow_dispatch: # So the whole chain can be triggered manually

jobs:
  job1:
    uses: ./.github/workflows/production-aws-deploy-blog-posts.yml
    secrets: inherit # Pass secrets if your sub-workflows need them

  job2:
    needs: job1
    uses: ./.github/workflows/production-aws-deploy-home-pages.yml
    secrets: inherit

  job3:
    needs: job2
    uses: ./.github/workflows/production-aws-deploy-tags.yml
    secrets: inherit